[2025-03-03T02:33:05.171+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:33:05.198+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_pipeline_gcs.validate_data scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-03T02:33:05.209+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_pipeline_gcs.validate_data scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-03T02:33:05.210+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-03-03T02:33:05.227+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): validate_data> on 2025-03-02 00:00:00+00:00
[2025-03-03T02:33:05.240+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=341) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-03T02:33:05.241+0000] {standard_task_runner.py:72} INFO - Started process 344 to run task
[2025-03-03T02:33:05.241+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scraping_pipeline_gcs', 'validate_data', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpztn_5kos']
[2025-03-03T02:33:05.242+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask validate_data
[2025-03-03T02:33:05.292+0000] {task_command.py:467} INFO - Running <TaskInstance: scraping_pipeline_gcs.validate_data scheduled__2025-03-02T00:00:00+00:00 [running]> on host 672a2cd6a90a
[2025-03-03T02:33:05.370+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping_pipeline_gcs' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-03T02:33:05.372+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-03T02:33:05.373+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-03T02:33:05.373+0000] {logging_mixin.py:190} INFO - Current task name:validate_data state:running start_date:2025-03-03 02:33:05.199119+00:00
[2025-03-03T02:33:05.374+0000] {logging_mixin.py:190} INFO - Dag name:scraping_pipeline_gcs and current dag run status:running
[2025-03-03T02:33:05.374+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:33:05.377+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 39, in validate_scraped_text
    raise AirflowFailException("No .txt files found after scraping!")
airflow.exceptions.AirflowFailException: No .txt files found after scraping!
[2025-03-03T02:33:05.389+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-03T02:33:05.390+0000] {logging_mixin.py:190} INFO - Task start:2025-03-03 02:33:05.199119+00:00 end:2025-03-03 02:33:05.389434+00:00 duration:0.190315
[2025-03-03T02:33:05.391+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): validate_data> dag:<DAG: scraping_pipeline_gcs> dagrun:<DagRun scraping_pipeline_gcs @ 2025-03-02 00:00:00+00:00: scheduled__2025-03-02T00:00:00+00:00, state:running, queued_at: 2025-03-03 02:32:09.979322+00:00. externally triggered: False>
[2025-03-03T02:33:05.391+0000] {logging_mixin.py:190} INFO - Failure caused by No .txt files found after scraping!
[2025-03-03T02:33:05.392+0000] {taskinstance.py:1226} INFO - Immediate failure requested. Marking task as FAILED. dag_id=scraping_pipeline_gcs, task_id=validate_data, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250303T023305, end_date=20250303T023305
[2025-03-03T02:33:05.418+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:33:05.419+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task validate_data (No .txt files found after scraping!; 344)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 39, in validate_scraped_text
    raise AirflowFailException("No .txt files found after scraping!")
airflow.exceptions.AirflowFailException: No .txt files found after scraping!
[2025-03-03T02:33:05.456+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-03T02:33:05.489+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:33:05.494+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
