[2025-03-02T22:38:10.725+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T22:38:10.734+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_pipeline_gcs.dvc_push manual__2025-03-02T22:36:54.012431+00:00 [queued]>
[2025-03-02T22:38:10.738+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_pipeline_gcs.dvc_push manual__2025-03-02T22:36:54.012431+00:00 [queued]>
[2025-03-02T22:38:10.738+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-03-02T22:38:10.742+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): dvc_push> on 2025-03-02 22:36:54.012431+00:00
[2025-03-02T22:38:10.752+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1020) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T22:38:10.753+0000] {standard_task_runner.py:72} INFO - Started process 1022 to run task
[2025-03-02T22:38:10.754+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scraping_pipeline_gcs', 'dvc_push', 'manual__2025-03-02T22:36:54.012431+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpv5iuh7tf']
[2025-03-02T22:38:10.754+0000] {standard_task_runner.py:105} INFO - Job 159: Subtask dvc_push
[2025-03-02T22:38:10.773+0000] {task_command.py:467} INFO - Running <TaskInstance: scraping_pipeline_gcs.dvc_push manual__2025-03-02T22:36:54.012431+00:00 [running]> on host 5e87a20f9330
[2025-03-02T22:38:10.807+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping_pipeline_gcs' AIRFLOW_CTX_TASK_ID='dvc_push' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T22:36:54.012431+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T22:36:54.012431+00:00'
[2025-03-02T22:38:10.807+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-02T22:38:10.808+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-02T22:38:10.808+0000] {logging_mixin.py:190} INFO - Current task name:dvc_push state:running start_date:2025-03-02 22:38:10.734773+00:00
[2025-03-02T22:38:10.808+0000] {logging_mixin.py:190} INFO - Dag name:scraping_pipeline_gcs and current dag run status:running
[2025-03-02T22:38:10.808+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T22:38:10.813+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-02T22:38:10.816+0000] {base.py:84} INFO - Retrieving connection 'gcp_service_account'
[2025-03-02T22:38:10.870+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 49, in dvc_push_to_gcs
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = credentials
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 719, in __setitem__
  File "<frozen os>", line 793, in encode
TypeError: str expected, not Credentials
[2025-03-02T22:38:10.880+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-02T22:38:10.880+0000] {logging_mixin.py:190} INFO - Task start:2025-03-02 22:38:10.734773+00:00 end:2025-03-02 22:38:10.880219+00:00 duration:0.145446
[2025-03-02T22:38:10.881+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): dvc_push> dag:<DAG: scraping_pipeline_gcs> dagrun:<DagRun scraping_pipeline_gcs @ 2025-03-02 22:36:54.012431+00:00: manual__2025-03-02T22:36:54.012431+00:00, state:running, queued_at: 2025-03-02 22:36:54.053326+00:00. externally triggered: True>
[2025-03-02T22:38:10.881+0000] {logging_mixin.py:190} INFO - Failure caused by str expected, not Credentials
[2025-03-02T22:38:10.881+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_pipeline_gcs, task_id=dvc_push, run_id=manual__2025-03-02T22:36:54.012431+00:00, execution_date=20250302T223654, start_date=20250302T223810, end_date=20250302T223810
[2025-03-02T22:38:10.905+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T22:38:10.906+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 159 for task dvc_push (str expected, not Credentials; 1022)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 49, in dvc_push_to_gcs
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = credentials
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 719, in __setitem__
  File "<frozen os>", line 793, in encode
TypeError: str expected, not Credentials
[2025-03-02T22:38:10.939+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-02T22:38:10.957+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T22:38:10.957+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
