[2025-03-02T07:57:34.622+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T07:57:34.630+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_pipeline_gcs.extract_data manual__2025-03-02T07:57:14.523004+00:00 [queued]>
[2025-03-02T07:57:34.633+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_pipeline_gcs.extract_data manual__2025-03-02T07:57:14.523004+00:00 [queued]>
[2025-03-02T07:57:34.634+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-03-02T07:57:34.638+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): extract_data> on 2025-03-02 07:57:14.523004+00:00
[2025-03-02T07:57:34.645+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=804) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T07:57:34.648+0000] {standard_task_runner.py:72} INFO - Started process 806 to run task
[2025-03-02T07:57:34.648+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scraping_pipeline_gcs', 'extract_data', 'manual__2025-03-02T07:57:14.523004+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6nrolgcw']
[2025-03-02T07:57:34.651+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask extract_data
[2025-03-02T07:57:34.686+0000] {task_command.py:467} INFO - Running <TaskInstance: scraping_pipeline_gcs.extract_data manual__2025-03-02T07:57:14.523004+00:00 [running]> on host 8b8ee4ab00d2
[2025-03-02T07:57:35.007+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping_pipeline_gcs' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T07:57:14.523004+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T07:57:14.523004+00:00'
[2025-03-02T07:57:35.008+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-02T07:57:35.008+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-02T07:57:35.008+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2025-03-02 07:57:34.630614+00:00
[2025-03-02T07:57:35.008+0000] {logging_mixin.py:190} INFO - Dag name:scraping_pipeline_gcs and current dag run status:running
[2025-03-02T07:57:35.008+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T07:57:35.009+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-02T07:57:35.009+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/src/scraping_script.py']
[2025-03-02T07:57:35.017+0000] {subprocess.py:99} INFO - Output:
[2025-03-02T07:57:35.047+0000] {subprocess.py:106} INFO - python: can't open file '/opt/***/dags/src/scraping_script.py': [Errno 2] No such file or directory
[2025-03-02T07:57:35.049+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-03-02T07:57:35.055+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-03-02T07:57:35.060+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-02T07:57:35.060+0000] {logging_mixin.py:190} INFO - Task start:2025-03-02 07:57:34.630614+00:00 end:2025-03-02 07:57:35.060269+00:00 duration:0.429655
[2025-03-02T07:57:35.060+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): extract_data> dag:<DAG: scraping_pipeline_gcs> dagrun:<DagRun scraping_pipeline_gcs @ 2025-03-02 07:57:14.523004+00:00: manual__2025-03-02T07:57:14.523004+00:00, state:running, queued_at: 2025-03-02 07:57:14.556147+00:00. externally triggered: True>
[2025-03-02T07:57:35.060+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-03-02T07:57:35.061+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_pipeline_gcs, task_id=extract_data, run_id=manual__2025-03-02T07:57:14.523004+00:00, execution_date=20250302T075714, start_date=20250302T075734, end_date=20250302T075735
[2025-03-02T07:57:35.075+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T07:57:35.075+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task extract_data (Bash command failed. The command returned a non-zero exit code 2.; 806)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-03-02T07:57:35.087+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-02T07:57:35.103+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T07:57:35.104+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
